[package]
name = "sub-triage-logs"
authors = ["Alexandru Vasile <alexandru.vasile@parity.io>"]
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive", "cargo"] }
log = "0.4"
tracing-subscriber = "0.3"
chrono = "0.4"
