[package]
name = "triage-logs"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive", "cargo"] }
log = "0.4"
env_logger = "0.11"
tracing-subscriber = "0.3"
chrono = "0.4"

